### PR TITLE
Ft signup

### PR DESCRIPTION
**Pull request by kbjude**

### CODE REVIEW

**Comment by shshamim63** [comment]
## Status :red_circle:  [!! Required Changes !!] :red_circle: 
___
Hi @kbjude  and @tunedev  :wave: ,
Awesome job on this project. All the items are rending on the place, where they should. That is really impressive for initial start. But there are some rooms that you have to cover to declare this project as complete :smile: . And i am definitely sure that you guys will cover them easily :sunglasses: .
___
#### Please Follow the instructions below :point_down: to complete this project.
___
### :spades: [Mandatory Changes] :spades: 
___
1. Stickler is not configured yet. Please follow this [link](https://github.com/microverseinc/linters-config/tree/master/css) to configure it. And it was mentioned on the pathwright.
stickler
2. Check HTML markup with this validator https://validator.w3.org/#validate_by_upload. You were also asked to do it too.
html
3. Form body down part text is not horizontally centered. Please fix it. 
image
___
### :clubs: [Optional Changes] :clubs: 
___
1. You can separate your reset CSS into a separate file. There are tons of template to reset the CSS. Suppose anyone want to participate on your code and the first priority is to change the reset CSS. Then he has to find out the portion of reset css and then have to replace it. And i think is not well organized.
2. As far i know the submit button of a form tag is situated outside of the form tag. You can check this [link](https://www.w3schools.com/tags/att_button_form.asp). If you find anything different don't forget to let me know.
___
##### Please fix the mentioned issues and don't forget to send another review request. :slightly_smiling_face: 
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Slack](Shakhawat Hossain)

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Files not related to the project should be removed. Validator errors should be fixed.

**Comment by pelzolga123** [comment]
## Hi Team!  
### Your project looks :+1: great!
But you have need to do more corrections:
* [ ] Check HTML markup with this [validator](https://validator.w3.org/#validate_by_upload). Now it shows errors in your project.
* [ ] Files not related to the project should not be committed and added to .gitignore (in your project you have `node modules` folder and `package-lock.json` file, that should be removed ) [Link to screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png)
* [ ] As previous review requires, form body down part text is not horizontally centered. Please fix it.

### Please kindly Fix the above issue and send another code review request.

If you have any questions or need help, you can message me on slack. *Happy coding*

**Review by nikasulo — APPROVED** [review]
# Really fantastic job guys! :rocket: 
Please go ahead and merge this beautiful piece of work :smile:.

**Pull request merged**
